### ISSUE TITLE
下载网易云音乐，应用音量中名称显示为“Cloud Music”

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#10]
预期结果：名称应汉化

Download Netease Cloud Music, the name in the app volume is displayed as "Cloud Music"

**Comment by fzx-h** [comment]
已解决

**Comment by fzx-h** [comment]
除了一些由网页封装的页面外，如腾讯视频

**Comment by liumin0322** [comment]
20200328版本测试通过。
