### ISSUE TITLE
使用网易云音乐，未进行音量调节，但通过插件查看自动播放至下一首时的默认音量被改变了

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#13]
With Netease Cloud Music, the volume is not adjusted, but the default volume when the auto-play to the next song is viewed through the plug-in has been changed

**Comment by fzx-h** [comment]
最新版已解决

**Comment by liumin0322** [comment]
默认播放至下一首，网易云音乐的应用音量进度条不显示

**Comment by fzx-h** [comment]
目前已优化，但还是存在有时候显示不全，暂时没有找到好的解决办法

**Comment by fzx-h** [comment]
已解决，对应commit：
Fixed Netease Cloud automatically switching to the next track when the volume adjustment was turned on, and the scroll bar disappeared

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
