### ISSUE TITLE
更改音量硬件设置后，任务栏右下角音量icon消失

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-media#14]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：
1. 右键点击音量
2. 设置音量，硬件
3. 点击内置音频，所选设备的设置将配置文件设置为关，再更改为默认设置

预期结果：设置为关后，右下角没有音量图标。改为默认值后音量图标出现。

实际结果：设置为关后，右下角没有音量图标，改为默认后还是没有音量图标。

**Comment by liumin0322** [comment]
设置为关后，右下角仍存在音量图标，输出设备音量显示为100%。

**Comment by fzx-h** [comment]
测试步骤：右键点击音量进入设置时，点击设备将配置文件改为关，只是修改了输出设备，图标并不会消失

**Comment by liumin0322** [comment]
20200314版本测试通过
