### ISSUE TITLE
网易云音乐自动播放至下一首，应用音量布局改变

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#16]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开一个应用播放
2、再打开网易云音乐，自动播放至下一首

预期结果：应用音量中布局正常

实际结果：应用音量中，两个应用音量显示排列很紧

**Comment by fzx-h** [comment]
目前已优化，但还是存在有时候显示不全，暂时没有找到好的解决办法

**Comment by fzx-h** [comment]
已解决，对应commit：
Fixed Netease Cloud automatically switching to the next track when the volume adjustment was turned on, and the scroll bar disappeared

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
