### ISSUE TITLE
应用音量中默认信息未汉化

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#17]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开音量插件

预期结果：默认无应用的提示信息应为中文

实际结果：提示信息应为英文

**Comment by fzx-h** [comment]
最新版已汉化

**Comment by liumin0322** [comment]
20200314版本测试通过
