### ISSUE TITLE
通过应用调节音量，插件中不会同步

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#18]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开网易云音乐播放音乐
2、通过应用调节音量大小，查看插件音量显示

预期结果：插件音量与应用音量大小同步

实际结果：插件音量无变化

**Comment by fzx-h** [comment]
最新版已解决

**Comment by liumin0322** [comment]
20200314版本测试通过
