### ISSUE TITLE
mini模式下的扬声器图标异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#19]
![2020-03-17 14-09-18屏幕截图](https://user-images.githubusercontent.com/48200161/76827070-e95fc580-6858-11ea-850b-80b2dc7fd27d.png)

**Comment by fzx-h** [comment]
由于主题图标里面暂时还未添加该图标，所以获取的图标有异常

**Comment by fzx-h** [comment]
已修改

**Comment by liumin0322** [comment]
20200328版本测试通过。
