### ISSUE TITLE
应用音量下，悬停无法获取当前设置值

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#21]

**Comment by liumin0322** [comment]
![2020-03-17 14-14-47屏幕截图](https://user-images.githubusercontent.com/48200161/76827406-afdb8a00-6859-11ea-8d1d-01ecb03969bc.png)

**Comment by fzx-h** [comment]
已添加点击和拖动时显示滑动条的值

**Comment by liumin0322** [comment]
点击时音量值闪现，悬浮时不会出现音量值

**Comment by fzx-h** [comment]
设计内容为点击或拖动的时候显示百分比值

**Comment by liumin0322** [comment]
通过点击修改音量大小时，弹出的显示为修改前音量大小，应为修改后音量大小

**Comment by fzx-h** [comment]
already fixed

**Comment by liumin0322** [comment]
Tested pass in 20200410 version
