### ISSUE TITLE
在打开音量调节的情况下，网易云自动切换至下一首，滚动条消失

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#22]
![2020-03-17 14-15-51屏幕截图](https://user-images.githubusercontent.com/48200161/76827524-f92bd980-6859-11ea-8b27-ddb03e824601.png)

**Comment by fzx-h** [comment]
目前已优化，但还是存在有时候显示不全，暂时没有找到好的解决办法

**Comment by fzx-h** [comment]
已解决，对应commit :
Fixed Netease Cloud automatically switching to the next track when the volume adjustment was turned on, and the scroll bar disappeared

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
