### ISSUE TITLE
“系统音量”的汉字显示不完全

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#23]
![2020-03-17 14-20-28屏幕截图](https://user-images.githubusercontent.com/48200161/76827754-840cd400-685a-11ea-8115-4fc9d7edeadb.png)

**Comment by fzx-h** [comment]
已解决

**Comment by liumin0322** [comment]
“系统音量”四个字字体大小不一致
![2020-03-21 10-44-28屏幕截图](https://user-images.githubusercontent.com/48200161/77217944-5331e500-6b61-11ea-9112-f2d0e820edca.png)

**Comment by handsome-feng** [comment]
Fixed.
