### ISSUE TITLE
在收纳栏中时，打开的窗口显示位置不正确

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#29]

**Comment by liumin0322** [comment]
![2020-03-30 17-46-37屏幕截图](https://user-images.githubusercontent.com/48200161/77898875-6d309d80-72ae-11ea-8b1b-2a36ada32834.png)

**Comment by fzx-h** [comment]
以解决

**Comment by fzx-h** [comment]
对应commit: Modify right-click menu position

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
