### ISSUE TITLE
【国际化】输出设备后存在一个[符号

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#30]
![Screenshot from 2020-04-03 15-45-00](https://user-images.githubusercontent.com/48200161/78336759-7e392180-75c2-11ea-96d0-ef517ae89160.png)

**Comment by fzx-h** [comment]
以解决，对应commit:
Modify the problem of incomplete internationalization display

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
