### ISSUE TITLE
【国际化】应用音量名称显示不完全

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#31]
![Screenshot from 2020-04-03 15-49-14](https://user-images.githubusercontent.com/48200161/78336974-cfe1ac00-75c2-11ea-9a16-6e5b984dcd85.png)

**Comment by fzx-h** [comment]
以解决，对应commit:
Modify the problem of incomplete internationalization display

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
