### ISSUE TITLE
【双屏扩展】扩展屏在上，主屏在下的情况下，音量调节左右键弹出窗口位置均显示异常 

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#32]
![2020-04-04 20-00-17屏幕截图](https://user-images.githubusercontent.com/48200161/78450142-009f0f80-76af-11ea-9c87-b74ce553bced.png)

**Comment by fzx-h** [comment]
以解决，对应commit:
Changed the method of obtaining the position and height of the taskbar from gsetting to dbus

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
