### ISSUE TITLE
what's the usage of this file : debian/ukui-media-server.postinst

### ISSUE THREAD

**Issue by dou-y** [ukui/ukui-media#40]
@handsome-feng  this file is supposed to run after package installed. but i found no ukui-media-server.service in the ubuntukylin os or this package. 
![图片](https://user-images.githubusercontent.com/59866026/86579424-e4618600-bfaf-11ea-8f25-84f75325188c.png)

**Comment by fzx-h** [comment]
Used to refresh gsettings value
