### ISSUE TITLE
打开程序后，使用键盘调节音量无效，且在应用音量页面，上下键为页面滑动效果

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#5]
After opening the program, using the keyboard to adjust the volume is invalid, and on the application volume page, the up and down keys are the page sliding effect

**Comment by liumin0322** [comment]
点开右下角音量调节，通过鼠标方向键调节音量无效，需要通过鼠标将焦点唤至音量杆，才可通过键盘调节。

**Comment by fzx-h** [comment]
最新设计稿只在mini模式下可上下左右键调节音量

**Comment by liumin0322** [comment]
20200314版本测试通过
