### ISSUE TITLE
The volume setting is not Chinese

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-media#54]
Version: 20.04LTS
Test environment: ThinkPad X1
Test steps:
Step 1. Click the volume icon on the taskbar
Step 2. View the number of output devices and applications
Expected results:
Step 1 pop-up window
Step 2 The display device is normal
actual results:
Step 1 is normal
Step 2 Check whether the output device and application volume display information is in Chinese

![image](https://user-images.githubusercontent.com/39893452/89092664-54fc9680-d3e6-11ea-9891-1980c10012f1.png)

**Comment by handsome-feng** [comment]
Fixed.
