### ISSUE TITLE
两个网页同时播放视频，应用音量刻度值不随调节而变化

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#7]
两个网页播放会显示3个firefox音量，其中两个音量值不随调节改变，始终显示为0和77

Two webpages play video at the same time, the application volume scale value does not change with adjustment

**Comment by fzx-h** [comment]
由于打开视频时，当前网页可能也在播放视频，所以导致有两个或以上的应用显示，目前需要等个10秒左右才能刷新出来显示成一个，调节这个播放视频声音输出是有效的
