### ISSUE TITLE
firefox播放视频，其中一个网页音量通过应用音量设置无效

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-media#9]
应用音量设置为0以后，仍有声音，仅通过系统音量设置有效

firefox play video, one of the webpage volume is invalid by applying volume setting

**Comment by fzx-h** [comment]
由于打开视频时，当前网页可能也在播放视频，所以导致有两个或以上的应用显示，目前需要等个10秒左右才能刷新出来显示成一个，调节这个播放视频声音输出是有效的
